# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DemoReports
                                 A QGIS plugin
 Generate demographic reports and datafills from block group data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-20
        copyright            : (C) 2026 by Retail Gravity
        email                : brad@retailgravity.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DemoReports class from file DemoReports.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .demo_reports import DemoReports
    return DemoReports(iface)
